services:
  db:
    image: mariadb:11.7-noble
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: dungeon_world_v2

  adminer:
    image: adminer:latest
    ports:
      - "9002:8080"
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    container_name: keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin  #
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin  #
      - KC_DB=mariadb #
      - KC_DB_URL=jdbc:mariadb://db:3306/keycloak?createDatabaseIfNotExist=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&enabledTLSProtocols=TLSv1,TLSv1.1,TLSv1.2
      - KC_DB_USERNAME=root #
      - KC_DB_PASSWORD=my-secret-pw  #
      - KC_HOSTNAME_STRICT=false

    command: ["start", "--http-enabled=true", "--verbose"]
    ports:
      - 8080:8080
    depends_on:
      - db
    restart: always

 
volumes:
  db_data:
  postgres_data: