services:
  db:
    image: mariadb:11.7-noble
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: dungeon_world_v2

  adminer:
    image: adminer:latest
    ports:
      - "9002:8080"
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    container_name: keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin  #
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin  #
      - KC_DB=postgres #
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak?createDatabaseIfNotExist=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&enabledTLSProtocols=TLSv1,TLSv1.1,TLSv1.2
      - KC_DB_USERNAME=keycloak #
      - KC_DB_PASSWORD=password  #
      - KC_HOSTNAME=localhost  #
      - KEYCLOAK_FRONTEND_URL=http://localhost:8080 
      - KEYCLOAK_LOGLEVEL=DEBUG  #
      - KC_HOSTNAME_PORT=8080  #
      - KC_HOSTNAME_STRICT_BACKCHANNEL=true #
      - KC_HEALTH_ENABLED=true

    command: ["start", "--http-enabled=true", "--verbose"]
    ports:
      - 8080:8080
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:17.4-alpine3.21
    container_name: postgres
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  db_data:
  postgres_data: