services:
  db:
    image: mariadb:11.7-noble
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: dungeon_world_v2

  adminer:
    image: adminer:latest
    ports:
      - "9002:8080"
    restart: always
volumes:
  db_data:
