// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Domain.Databases;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250320220517_UpdateModels")]
    partial class UpdateModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Habilidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Carisma")
                        .HasColumnType("int");

                    b.Property<int>("Constituicao")
                        .HasColumnType("int");

                    b.Property<int>("Destreza")
                        .HasColumnType("int");

                    b.Property<int>("Forca")
                        .HasColumnType("int");

                    b.Property<int>("Inteligencia")
                        .HasColumnType("int");

                    b.Property<int>("Sabedoria")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Habilidades");
                });

            modelBuilder.Entity("backend.Models.Personagem", b =>
                {
                    b.Property<long>("PersonagemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("PersonagemId"));

                    b.Property<int>("Armadura")
                        .HasColumnType("int");

                    b.Property<string>("Classe")
                        .HasColumnType("longtext");

                    b.Property<int>("DadoDano")
                        .HasColumnType("int");

                    b.Property<string>("DescricaoDois")
                        .HasColumnType("longtext");

                    b.Property<string>("DescricaoUm")
                        .HasColumnType("longtext");

                    b.Property<string>("Equipamento")
                        .HasColumnType("longtext");

                    b.Property<int?>("HabilidadeId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<int>("Pv")
                        .HasColumnType("int");

                    b.Property<int>("PvTotal")
                        .HasColumnType("int");

                    b.HasKey("PersonagemId");

                    b.HasIndex("HabilidadeId");

                    b.ToTable("Personagens");
                });

            modelBuilder.Entity("backend.Models.Personagem", b =>
                {
                    b.HasOne("backend.Models.Habilidade", "Habilidade")
                        .WithMany()
                        .HasForeignKey("HabilidadeId");

                    b.Navigation("Habilidade");
                });
#pragma warning restore 612, 618
        }
    }
}
